[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 1_000_000

[rpc_endpoints]
goerli = "https://eth-goerli.public.blastapi.io"
sepolia = "https://eth-sepolia.public.blastapi.io"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}", chain = "goerli" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
